# Generated by Django 4.1.5 on 2023-01-26 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='order.order', verbose_name='주문'),
            preserve_default=False,
        ),
    ]
