# Generated by Django 4.1.5 on 2023-01-26 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_comment_order'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='shinhan_order_comment',
        ),
    ]
