# Generated by Django 4.1.5 on 2023-01-26 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='tel',
        ),
    ]
